import crypto from "crypto";
import { attrBool, attrString, getItem, putItem } from "@/lib/dynamodb";
import { isValidEmail, normalizeEmail } from "@/lib/unsubscribe-token";

export const ALLOWED_RECIPIENT_SOURCES = [
  "existing_customer",
  "contact_form",
  "meeting_request",
  "confirmed_subscriber",
] as const;

export type AllowedRecipientSource = (typeof ALLOWED_RECIPIENT_SOURCES)[number];

export type EligibilityResult = {
  email: string;
  allowed: boolean;
  reason:
    | "eligible"
    | "invalid_email"
    | "unknown_recipient"
    | "disallowed_source"
    | "unsubscribed"
    | "bounced"
    | "complained";
  source?: string;
};

function recipientPk(email: string) {
  return `RECIPIENT#${normalizeEmail(email)}`;
}

export async function registerEligibleRecipient(
  email: string,
  source: AllowedRecipientSource,
  metadata?: { consentAt?: Date; sourceDetail?: string }
): Promise<void> {
  const normalized = normalizeEmail(email);
  if (!isValidEmail(normalized)) throw new Error("Invalid email address.");
  if (!ALLOWED_RECIPIENT_SOURCES.includes(source)) {
    throw new Error("Recipient source is not allowed for SES delivery.");
  }

  const pk = recipientPk(normalized);
  const existing = await getItem(pk);
  const now = new Date().toISOString();

  // Never silently clear an unsubscribe/bounce/complaint. A new form submission
  // should not bypass an existing suppression record. Re-subscription should be
  // an explicit, separately audited action if you add it later.
  await putItem({
    ...(existing || {}),
    pk: { S: pk },
    email: { S: normalized },
    source: { S: source },
    sourceDetail: { S: metadata?.sourceDetail || source },
    consentAt: { S: (metadata?.consentAt || new Date()).toISOString() },
    unsubscribed: { BOOL: attrBool(existing, "unsubscribed") },
    bounced: { BOOL: attrBool(existing, "bounced") },
    complained: { BOOL: attrBool(existing, "complained") },
    createdAt: existing?.createdAt || { S: now },
    updatedAt: { S: now },
  });
}

export async function getEmailEligibility(email: string): Promise<EligibilityResult> {
  const normalized = normalizeEmail(email);
  if (!isValidEmail(normalized)) {
    return { email: normalized, allowed: false, reason: "invalid_email" };
  }

  const item = await getItem(recipientPk(normalized));
  if (!item) {
    return { email: normalized, allowed: false, reason: "unknown_recipient" };
  }

  const source = attrString(item, "source") || "unknown";
  if (!ALLOWED_RECIPIENT_SOURCES.includes(source as AllowedRecipientSource)) {
    return { email: normalized, allowed: false, reason: "disallowed_source", source };
  }
  if (attrBool(item, "complained")) {
    return { email: normalized, allowed: false, reason: "complained", source };
  }
  if (attrBool(item, "bounced")) {
    return { email: normalized, allowed: false, reason: "bounced", source };
  }
  if (attrBool(item, "unsubscribed")) {
    return { email: normalized, allowed: false, reason: "unsubscribed", source };
  }

  return { email: normalized, allowed: true, reason: "eligible", source };
}

export async function assertEmailCanBeSent(email: string): Promise<void> {
  const result = await getEmailEligibility(email);
  if (!result.allowed) {
    throw new Error(`SES delivery blocked for ${result.email}: ${result.reason}`);
  }
}

export async function unsubscribeEmail(email: string): Promise<"unsubscribed" | "already_unsubscribed"> {
  const normalized = normalizeEmail(email);
  const pk = recipientPk(normalized);
  const existing = await getItem(pk);
  const now = new Date().toISOString();

  if (existing && attrBool(existing, "unsubscribed")) {
    return "already_unsubscribed";
  }

  // A valid signed token is sufficient proof that the address was included in an email
  // generated by this application. Preserve known recipient metadata when available.
  await putItem({
    ...(existing || {}),
    pk: { S: pk },
    email: { S: normalized },
    source: existing?.source || { S: "confirmed_subscriber" },
    unsubscribed: { BOOL: true },
    unsubscribedAt: { S: now },
    updatedAt: { S: now },
    createdAt: existing?.createdAt || { S: now },
  });

  await putItem({
    pk: { S: `EVENT#${crypto.randomUUID()}` },
    type: { S: "unsubscribe" },
    email: { S: normalized },
    createdAt: { S: now },
    source: { S: "flexlabconnect.com" },
  });

  return "unsubscribed";
}

export async function markEmailRiskEvent(
  email: string,
  event: "bounce" | "complaint"
): Promise<void> {
  const normalized = normalizeEmail(email);
  const pk = recipientPk(normalized);
  const existing = await getItem(pk);
  const now = new Date().toISOString();

  await putItem({
    ...(existing || {}),
    pk: { S: pk },
    email: { S: normalized },
    source: existing?.source || { S: "existing_customer" },
    bounced: { BOOL: event === "bounce" || attrBool(existing, "bounced") },
    complained: { BOOL: event === "complaint" || attrBool(existing, "complained") },
    updatedAt: { S: now },
    createdAt: existing?.createdAt || { S: now },
  });
}
